// <auto-generated />
using CargoTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116114826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("CargoTracker.Models.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityTEU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentPort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IMO")
                        .IsUnique();

                    b.ToTable("Vessels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityTEU = 23800,
                            CurrentPort = "Singapore",
                            IMO = "IMO9125050",
                            Name = "EVER ACE",
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            CapacityTEU = 15800,
                            CurrentPort = "Mumbai",
                            IMO = "IMO9787301",
                            Name = "HMM ALGEBRAS",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
